Repository prachi320/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#4 recursion
  Recursion/Exponent.cpp
  Recursion/Permutation.cpp
  Recursion/SearchIngArray.cpp
  Recursion/SortedAndUnsorted.cpp
  Recursion/Sum_of_array.cpp
  Recursion/a.exe
  Recursion/boardPath.cpp
  Recursion/checkIsArrayIsSorted.cpp
  Recursion/digitsum.cpp
  Recursion/factorial.cpp
  Recursion/fibonacci.cpp
  Recursion/knapsackProblem.cpp
  Recursion/moveAllXAtLast.cpp
  Recursion/printNumber.cpp
  Recursion/printSpelling.cpp
  Recursion/removeDuplicatesInString.cpp
  Recursion/replacePi.cpp
  Recursion/reverseString.cpp
  Recursion/stairCase.cpp
  Recursion/stringPremutation.cpp
  Recursion/subSequence.cpp
  Recursion/subSets.cpp
  Recursion/subString.cpp
  Recursion/towerOfHanoi.cpp
Labels: documentation, enhancement, good first issue, #hacktoberfest2022, #c++

#6 Update MargeSort.cpp
  Sorting/MargeSort.cpp
Labels: #hacktoberfest2022, #HACKTOBERFEST-ACCEPTED

#7 heap problem s
  Heep/ArraySort.cpp
  Heep/a.exe
  Heep/medianInArray.cpp
Labels: #hacktoberfest2022, #HACKTOBERFEST-ACCEPTED

#8 Update selectionsort.cpp
  Sorting/selectionsort.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#10 python game
  dino/main.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#9 Number Theory Algorithms and Questions
  Number Theory/L01_0_primality_test.cpp
  Number Theory/L01_1primality_codechef.cpp
  Number Theory/L02_01sieve_of_eratosthenes.cpp
  Number Theory/L02_2_kth_prime.cpp
  Number Theory/L03_Prime_factaorization.cpp
  Number Theory/L04_0_Binary_exponentiation.cpp
  Number Theory/L04_1_Prime_Interval.cpp
  Number Theory/L04_2_micro_and_prime.cpp
  Number Theory/L05_prime_factorization_sieve.cpp
  Number Theory/L06_Matrix_Exponentiation.cpp
  Number Theory/L07_Fibonacci_finding.cpp
  Number Theory/L08_1_Euclid_Algorithm_GCD.cpp
  Number Theory/L08_2_gcd_queries.cpp
  Number Theory/L09_10_summary.cpp
  Number Theory/L10_1_Arpa_hard_exam.cpp
  Number Theory/L11_Modular_GCD.cpp
  Number Theory/L13_modulo_inverse.cpp
  Number Theory/L14_Total_divisors.cpp
  Number Theory/L15_Binomial_coefficient.cpp
  Number Theory/L18_Etf_root_of_n.cpp
  Number Theory/L19_etf_using_sieve.cpp
  Number Theory/L20_21gcd_sums.cpp
  Number Theory/L22_segmented_sieve.cpp
  Number Theory/L23_Common_divisors_efficient.cpp
  Number Theory/Sieve    of    Eratosthenes.pptx
  Number Theory/tempCodeRunnerFile.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#1 Create Radix_sort.cpp
  Sorting/Radix_sort.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED
